<?php

defined('_PS_VERSION_') or exit;

class NovElementorPage extends ObjectModel {
    const TPL_LANG = 1;
    const TPL_SHOP = 1;
    const TPL_ACTIVE = 2;

    public $id_employee;
    public $id_page = 0;
    public $type;
    public $title;
    public $data;
    public $active;
    public $date_add;
    public $date_upd;

    public static $definition = array(
        'table' => 'novelementor',
        'primary' => 'id',
        'multilang' => true,
        'multilang_shop' => true,
        'fields' => array(
            'id_employee' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId'),
            'id_page' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId'),
            'type' => array('type' => self::TYPE_STRING, 'validate' => 'isHookName', 'required' => true, 'size' => 100),
            'active' => array('type' => self::TYPE_INT, 'validate' => 'isUnsignedInt'),
            'date_add' => array('type' => self::TYPE_DATE, 'validate' => 'isDate'),
            'date_upd' => array('type' => self::TYPE_DATE, 'validate' => 'isDate'),
            'title' => array('type' => self::TYPE_STRING, 'lang' => true, 'validate' => 'isGenericName', 'size' => 255),
            'data' => array('type' => self::TYPE_NOTHING, 'lang' => true, 'validate' => 'isAnything'),
        ),
    );

    public function addTpl($auto_date = true, $null_values = false) {
        $db = Db::getInstance();

        if (isset($this->id) && !$this->force_id) {
            unset($this->id);
        }

        Hook::exec('actionObjectAddBefore', array('object' => $this));
        Hook::exec('actionObject' . get_class($this) . 'AddBefore', array('object' => $this));

        if ($auto_date && property_exists($this, 'date_add')) {
            $this->date_add = date('Y-m-d H:i:s');
        }

        if ($auto_date && property_exists($this, 'date_upd')) {
            $this->date_upd = date('Y-m-d H:i:s');
        }

        if (!$result = $db->insert($this->def['table'], $this->getFields(), $null_values)) {
            return false;
        }

        $this->id = $db->Insert_ID();

        if (!empty($this->def['multilang'])) {
            $fields = $this->getFieldsLang();
            if ($fields && is_array($fields)) {
                foreach ($fields as $field) {
                    foreach (array_keys($field) as $key) {
                        if (!Validate::isTableOrIdentifier($key)) {
                            throw new PrestaShopException('key ' . $key . ' is not table or identifier');
                        }
                    }
                    $field[$this->def['primary']] = (int) $this->id;
                    $field['id_shop'] = self::TPL_SHOP;

                    $result &= $db->insert($this->def['table'] . '_lang', $field);
                }
            }
        }

        Hook::exec('actionObjectAddAfter', array('object' => $this));
        Hook::exec('actionObject' . get_class($this) . 'AddAfter', array('object' => $this));

        return $result;
    }

    public function add($auto_date = true, $null_values = false)
    {
        //return parent::add($auto_date, $null_values); // TODO: Change the autogenerated stub

        $context = Context::getContext();

        $this->id_employee = $context->employee->id;
        $this->active = (int)$this->active;

        $result = $this->active == self::TPL_ACTIVE ? $this->addTpl($auto_date, $null_values) : parent::add($auto_date, $null_values);

        if ($result && !$this->id_page && $this->active <= 1 && $this->type && !empty($context->controller->module)) {
            $context->controller->module->registerHook($this->type, Shop::getContextListShopID(), null);
        }
        return $result;
    }

    public function update($null_values = false)
    {
        //return parent::update($null_values); // TODO: Change the autogenerated stub

        $context = Context::getContext();

        $old_data = $this->id_page ? null : new NovElementorPage($this->id);
        $this->active = (int) $this->active;
        $result = parent::update($null_values);

        if ($result && !$this->id_page && $this->active <= 1) {
            $module = $context->controller->module;
            if ($old_data->type && !method_exists($module, 'hook' . $old_data->type) && !self::getIdByPage($old_data->type, 0)) {
                $module->unregisterHook($old_data->type, Shop::getContextListShopID());
            }
            empty($this->type) or $module->registerHook($this->type, Shop::getContextListShopID(), null);
        }

        return $result;
    }

    public function delete()
    {
        // return parent::delete(); // TODO: Change the autogenerated stub

        $context = Context::getContext();

        $id = (int)$this->id;
        $result = parent::delete();

        if ($result) {
            $module = $context->controller->module;
            $shops = Shop::getContextListShopID();

            if (!$this->id_page && !method_exists($module, 'hook' . $this->type) && !self::getIdByPage($this->type, 0)) {
                $module->unregisterHook($this->type, $shops);
            }
        }

        return $result;
    }

    public function getFieldsLang()
    {
        // return parent::getFieldsLang(); // TODO: Change the autogenerated stub

        $fieldsLang = parent::getFieldsLang();
        $db = Db::getInstance();
        foreach ($fieldsLang as &$fields) {
            if (!empty($fields['data'])) {
                $fields['data'] = $db->escape($fields['data'], true);
            }
        }
        return $fieldsLang;
    }

    public static function displayFieldName($field, $class = __CLASS__, $htmlentities = true, Context $context = null)
    {
        // return parent::displayFieldName($field, $class, $htmlentities, $context); // TODO: Change the autogenerated stub

        if ($field == 'type') {
            return 'Position';
        }
        else {
            return parent::displayFieldName($field, $class, $htmlentities, $context);
        }
    }

    public static function getInstance($type, $id_page)
    {
        $id = self::getIdByPage($type, $id_page);

        if ($id) {
            $elem = new NovElementorPage($id);
        } else {
            $elem = new NovElementorPage();
            $elem->id_page = $id_page;
            $elem->type = $type;
            $elem->active = true;
            $elem->title = array();
            $elem->data = array();
        }
        return $elem;
    }

    public static function deleteInstance($type, $id_page)
    {
        $id = self::getIdByPage($type, $id_page);

        if ($id) {
            $page = new NovElementorPage($id);
            return $page->delete();
        }
        return false;
    }

    public static function getData($type, $id_page, $id_lang = 0, $id_shop = 0)
    {
        $ctx = Context::getContext();
        $table = _DB_PREFIX_ . self::$definition['table'];
        $type = preg_replace('~\W+~', '', $type);
        $id_page = (int) $id_page;
        $id_lang = (int) $id_lang;
        $id_shop = (int) $id_shop;

        if (!$id_lang) {
            $id_lang = (int) $ctx->language->id;
        }
        if (!$id_shop && Shop::isFeatureActive()) {
            $id_shop = (int) $ctx->shop->id;
        }

        return Db::getInstance()->getValue(
            "SELECT b.data FROM $table a
            INNER JOIN {$table}_lang b ON a.id = b.id
            WHERE b.id_lang = $id_lang AND a.id_page = $id_page AND a.type LIKE '$type'" .
            ($id_shop ? ' AND b.id_shop = ' . $id_shop : '')
        );
    }

    public static function getDataRows($type, $active = true, $id_page = 0, $id_lang = 0, $id_shop = 0, $limit = 0)
    {
        $ctx = Context::getContext();
        $table = _DB_PREFIX_ . self::$definition['table'];
        $type = preg_replace('~\W+~', '', $type);
        $active = (int) $active;
        $id_page = (int) $id_page;
        $id_lang = (int) $id_lang;
        $id_shop = (int) $id_shop;
        $limit = (int) $limit;

        if (!$id_lang) {
            $id_lang = (int) $ctx->language->id;
        }
        if (!$id_shop && Shop::isFeatureActive()) {
            $id_shop = (int) $ctx->shop->id;
        }

        $res = Db::getInstance()->executeS(
            "SELECT a.id, b.id_lang, b.id_shop, b.data FROM $table a
            LEFT JOIN {$table}_lang AS b ON a.id = b.id
            LEFT JOIN {$table}_shop sa ON sa.id = a.id AND sa.id_shop = b.id_shop
            WHERE b.id_lang = $id_lang AND a.id_page = $id_page AND a.type LIKE '$type'" .
            ($id_shop ? ' AND sa.id_shop = ' . $id_shop : '') .
            ($active ? ' AND a.active = ' . $active : '') .
            ($limit ? ' LIMIT ' . $limit : '')
        );

        return $res ? $res : array();
    }

    public static function getIdByPage($type, $id_page)
    {
        $table = _DB_PREFIX_ . self::$definition['table'];
        $type = preg_replace('~\W+~', '', $type);
        $id_page = (int) $id_page;

        return Db::getInstance()->getValue("SELECT id FROM $table WHERE id_page = $id_page AND type LIKE '$type'");
    }

    public static function getLangIdsByPage($type, $id_page, $id_shop = 0)
    {
        $table = _DB_PREFIX_ . self::$definition['table'];
        $type = preg_replace('~\W+~', '', $type);
        $id_page = (int) $id_page;
        $id_shop = (int) $id_shop;

        if (!$id_shop && Shop::isFeatureActive()) {
            $id_shop = Context::getContext()->shop->id;
        }

        $rows = Db::getInstance()->executeS(
            "SELECT id_lang FROM $table a
            LEFT JOIN {$table}_lang b ON a.id = b.id
            LEFT JOIN {$table}_shop sa ON sa.id = a.id AND sa.id_shop = b.id_shop
            WHERE a.id_page = $id_page AND a.type LIKE '$type' AND b.data != ''" .
            ($id_shop ? ' AND sa.id_shop = ' . $id_shop : '')
        );

        $res = array();
        foreach ($rows as $row) {
            $res[] = $row['id_lang'];
        }

        return $res;
    }
}